/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author Nikho
 */
public final class FormBukuAlamat extends javax.swing.JFrame {
    private DefaultTableModel daftarTBL_Kontak;
    private String SQL;
    
    public void lebarkolom(){
        //coding untuk mengatur lebar kolom dalam tabel
        TableColumn column;
        kontakTBL.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = kontakTBL.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = kontakTBL.getColumnModel().getColumn(1); 
        column.setPreferredWidth(100); 
        column = kontakTBL.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = kontakTBL.getColumnModel().getColumn(3); 
        column.setPreferredWidth(100);
        column = kontakTBL.getColumnModel().getColumn(4); 
        column.setPreferredWidth(70); 
        column = kontakTBL.getColumnModel().getColumn(5); 
        column.setPreferredWidth(100); 
        column = kontakTBL.getColumnModel().getColumn(6); 
        column.setPreferredWidth(170); 
        column = kontakTBL.getColumnModel().getColumn(7); 
        column.setPreferredWidth(300); 
        column = kontakTBL.getColumnModel().getColumn(8); 
        column.setPreferredWidth(150);  
    }
    
    public void Tampilkandata() {
        //coding untuk meampilkan data dalam tabel
        daftarTBL_Kontak = new DefaultTableModel();
        daftarTBL_Kontak.addColumn("ID");
        daftarTBL_Kontak.addColumn("Nama");
        daftarTBL_Kontak.addColumn("Jenis Kelamin");
        daftarTBL_Kontak.addColumn("Tanggal Lahir");
        daftarTBL_Kontak.addColumn("Agama");
        daftarTBL_Kontak.addColumn("No. Telepon");
        daftarTBL_Kontak.addColumn("Email");
        daftarTBL_Kontak.addColumn("Alamat");
        daftarTBL_Kontak.addColumn("Keterangan");
        
        kontakTBL.setModel(daftarTBL_Kontak);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from kontak";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()){
                daftarTBL_Kontak.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("jk"),
                    res.getString("tanggal"),
                    res.getString("agama"),
                    res.getString("telepon"),
                    res.getString("email"),
                    res.getString("alamat"),
                    res.getString("keterangan") });
            }
        lebarkolom();
        
        //coding untuk menampilkan jumlah kontak yang ada pada tabel
        int i = daftarTBL_Kontak.getRowCount();
        jumlahKontakLB.setText(""+i);
        
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void kosong(){
        // coding untuk mengosongkan textfield dan radio button
        idTF.setText("");
        namaTF.setText("");
        tanggalTF.setText("");
        agamaTF.setText("");
        teleponTF.setText("");
        emailTF.setText("");
        alamatTA.setText("");
        keteranganTA.setText("");
        jeniskelaminBTGroup.clearSelection();
        cariTF.setText("");
    }
    
    private boolean isIdExists(String id) throws SQLException {
    String query = "SELECT COUNT(*) FROM kontak WHERE id = ?";
    Connection conn = Koneksi.getConnection();
    java.sql.PreparedStatement pst = conn.prepareStatement(query);
    pst.setString(1, id);
    ResultSet rs = pst.executeQuery();
    rs.next();
    int count = rs.getInt(1);
    return count > 0;
    }
    
    /**
     * Creates new form HomeBukuAlamat
     */
    public FormBukuAlamat() {
        initComponents();
        this.Tampilkandata();
        lebarkolom();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelaminBTGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jumlahKontakLB = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        namaTF = new javax.swing.JTextField();
        tanggalTF = new javax.swing.JTextField();
        cariTF = new javax.swing.JTextField();
        teleponTF = new javax.swing.JTextField();
        agamaTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        kontakTBL = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        keteranganTA = new javax.swing.JTextArea();
        simpanBT = new javax.swing.JButton();
        ubahBT = new javax.swing.JButton();
        kosongkanBT = new javax.swing.JButton();
        hapusBT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        perempuanRB = new javax.swing.JRadioButton();
        lakilakiRB = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        BukuIcon = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Buku Alamat");
        setName("formBukuAlamat"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1210, 800));

        jPanel1.setBackground(new java.awt.Color(7, 26, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. Telepon");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Lahir");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Kelamin");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Keterangan");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cari");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Agama");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kontak :");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");

        jumlahKontakLB.setForeground(new java.awt.Color(255, 255, 255));
        jumlahKontakLB.setText("0");

        cariTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariTFKeyReleased(evt);
            }
        });

        kontakTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kontakTBLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kontakTBL);

        alamatTA.setColumns(20);
        alamatTA.setLineWrap(true);
        alamatTA.setRows(3);
        alamatTA.setWrapStyleWord(true);
        jScrollPane2.setViewportView(alamatTA);

        keteranganTA.setColumns(20);
        keteranganTA.setLineWrap(true);
        keteranganTA.setRows(3);
        keteranganTA.setWrapStyleWord(true);
        jScrollPane3.setViewportView(keteranganTA);

        simpanBT.setText("Simpan");
        simpanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBTActionPerformed(evt);
            }
        });

        ubahBT.setText("Ubah");
        ubahBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBTActionPerformed(evt);
            }
        });

        kosongkanBT.setText("Kosongkan");
        kosongkanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kosongkanBTActionPerformed(evt);
            }
        });

        hapusBT.setText("Hapus");
        hapusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBTActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(7, 26, 51));

        jeniskelaminBTGroup.add(perempuanRB);
        perempuanRB.setForeground(new java.awt.Color(255, 255, 255));
        perempuanRB.setText("Perempuan");

        jeniskelaminBTGroup.add(lakilakiRB);
        lakilakiRB.setForeground(new java.awt.Color(255, 255, 255));
        lakilakiRB.setText("Laki-Laki");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lakilakiRB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(perempuanRB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lakilakiRB)
                    .addComponent(perempuanRB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 174, 239));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 55));

        BukuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoBuku.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(7, 26, 51));
        jLabel12.setText("APLIKASI BUKU ALAMAT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BukuIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(890, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(BukuIcon))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teleponTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(34, 34, 34)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel3))
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jumlahKontakLB))
                    .addComponent(jLabel1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpanBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubahBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kosongkanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teleponTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpanBT)
                    .addComponent(ubahBT)
                    .addComponent(kosongkanBT)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hapusBT)
                        .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jumlahKontakLB))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void kosongkanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kosongkanBTActionPerformed
        kosong();
    }//GEN-LAST:event_kosongkanBTActionPerformed

    private void simpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTActionPerformed
        try {
            String pilihanJK = "";
            if (lakilakiRB.isSelected()) {
                pilihanJK = lakilakiRB.getText();
            } else if (perempuanRB.isSelected()) {
                pilihanJK = perempuanRB.getText();
            }
            
            if (idTF.getText().isEmpty() || namaTF.getText().isEmpty() || pilihanJK.isEmpty()
                || tanggalTF.getText().isEmpty() || agamaTF.getText().isEmpty()
                || teleponTF.getText().isEmpty() || emailTF.getText().isEmpty()
                || alamatTA.getText().isEmpty() || keteranganTA.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Semua kolom harus diisi");
                    return; 
                }
            
            if (isIdExists(idTF.getText())) {
                JOptionPane.showMessageDialog(this, "ID sudah terdaftar. Gunakan ID lain.");
                return;
            }
            
            String sql = "INSERT INTO kontak VALUES"
                    + "('"+idTF.getText()+"','"+namaTF.getText()+"','"+pilihanJK+"',"
                    + "'"+tanggalTF.getText()+"','"+agamaTF.getText()+"','"+teleponTF.getText()+"',"
                    + "'"+emailTF.getText()+"','"+alamatTA.getText()+"','"+keteranganTA.getText()+"')";
            Connection conn = Koneksi.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Tampilkandata();
        kosong();
    }//GEN-LAST:event_simpanBTActionPerformed

    private void hapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTActionPerformed
        try {
        if (idTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silakan isi ID terlebih dahulu");
            return;
        }
            
        Object[] options = {"Iya", "Tidak"};
        int konfirmasi = JOptionPane.showOptionDialog(
                null,
                "Apakah Anda yakin ingin menghapus data?",
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM kontak WHERE id='"+idTF.getText()+"'";
                Connection conn = Koneksi.getConnection();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Tampilkandata();
        kosong();
    }//GEN-LAST:event_hapusBTActionPerformed

    private void ubahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBTActionPerformed
        try {
            String pilihanJK = "";
            if (lakilakiRB.isSelected()) {
                pilihanJK = lakilakiRB.getText();
            } else if (perempuanRB.isSelected()) {
                pilihanJK = perempuanRB.getText();
            }
            
            if (namaTF.getText().isEmpty() || pilihanJK.isEmpty() || tanggalTF.getText().isEmpty()
                || agamaTF.getText().isEmpty() || teleponTF.getText().isEmpty()
                || emailTF.getText().isEmpty() || alamatTA.getText().isEmpty()
                || keteranganTA.getText().isEmpty() || idTF.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Semua kolom harus diisi");
                    return; 
                }
            
            String sql = "UPDATE kontak SET nama ="
                    + "'"+namaTF.getText()+"', jk = '"+pilihanJK+"',"
                    + "tanggal = '"+tanggalTF.getText()+"', agama = '"+agamaTF.getText()+"', telepon = '"+teleponTF.getText()+"',"
                    + "email = '"+emailTF.getText()+"', alamat = '"+alamatTA.getText()+"', keterangan = '"+keteranganTA.getText()+"'"
                    + "WHERE id = '"+idTF.getText()+"'";
            Connection conn = Koneksi.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Tampilkandata();
        kosong();
    }//GEN-LAST:event_ubahBTActionPerformed

    private void cariTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTFKeyReleased
        daftarTBL_Kontak = new DefaultTableModel();
        daftarTBL_Kontak.addColumn("ID");
        daftarTBL_Kontak.addColumn("Nama");
        daftarTBL_Kontak.addColumn("Jenis Kelamin");
        daftarTBL_Kontak.addColumn("Tanggal Lahir");
        daftarTBL_Kontak.addColumn("Agama");
        daftarTBL_Kontak.addColumn("No. Telepon");
        daftarTBL_Kontak.addColumn("Email");
        daftarTBL_Kontak.addColumn("Alamat");
        daftarTBL_Kontak.addColumn("Keterangan");
        
        kontakTBL.setModel(daftarTBL_Kontak);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from kontak where nama like '%"+cariTF.getText()+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()){
                daftarTBL_Kontak.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("jk"),
                    res.getString("tanggal"),
                    res.getString("agama"),
                    res.getString("telepon"),
                    res.getString("email"),
                    res.getString("alamat"),
                    res.getString("keterangan") });
            }
            lebarkolom();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_cariTFKeyReleased

    private void kontakTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kontakTBLMouseClicked
        int baris = kontakTBL.rowAtPoint(evt.getPoint());
        String id =kontakTBL.getValueAt(baris, 0).toString();
        idTF.setText(id);
        String nama =kontakTBL.getValueAt(baris, 1).toString();
        namaTF.setText(nama);
        
        String jenisKelamin = kontakTBL.getValueAt(baris, 2).toString();
        if (jenisKelamin.equals("Laki-Laki")) {
            lakilakiRB.setSelected(true);
            perempuanRB.setSelected(false);
        } else if (jenisKelamin.equals("Perempuan")) {
            lakilakiRB.setSelected(false);
            perempuanRB.setSelected(true);
        } else {
            lakilakiRB.setSelected(false);
            perempuanRB.setSelected(false);
        }
        
        String tanggal =kontakTBL.getValueAt(baris, 3).toString();
        tanggalTF.setText(tanggal);
        String agama =kontakTBL.getValueAt(baris, 4).toString();
        agamaTF.setText(agama);
        String telepon =kontakTBL.getValueAt(baris, 5).toString();
        teleponTF.setText(telepon);
        String email =kontakTBL.getValueAt(baris, 6).toString();
        emailTF.setText(email);
        String alamat =kontakTBL.getValueAt(baris, 7).toString();
        alamatTA.setText(alamat);
        String keterangan =kontakTBL.getValueAt(baris, 8).toString();
        keteranganTA.setText(keterangan);
    }//GEN-LAST:event_kontakTBLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BukuIcon;
    private javax.swing.JTextField agamaTF;
    private javax.swing.JTextArea alamatTA;
    private javax.swing.JTextField cariTF;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton hapusBT;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.ButtonGroup jeniskelaminBTGroup;
    private javax.swing.JLabel jumlahKontakLB;
    private javax.swing.JTextArea keteranganTA;
    private javax.swing.JTable kontakTBL;
    private javax.swing.JButton kosongkanBT;
    private javax.swing.JRadioButton lakilakiRB;
    private javax.swing.JTextField namaTF;
    private javax.swing.JRadioButton perempuanRB;
    private javax.swing.JButton simpanBT;
    private javax.swing.JTextField tanggalTF;
    private javax.swing.JTextField teleponTF;
    private javax.swing.JButton ubahBT;
    // End of variables declaration//GEN-END:variables
}
