/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Nikho
 */
public class LoginBukuAlamat extends javax.swing.JFrame {

    /**
     * Creates new form LoginBukuAlamat
     */
    public LoginBukuAlamat() {
        initComponents();
        
        //Strecth Image agar menyesuaikan panjang dan lebar JLabel
        Icon i = bgLoginLB.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(bgLoginLB.getWidth(), bgLoginLB.getHeight(), Image.SCALE_SMOOTH);
        bgLoginLB.setIcon(new ImageIcon(image));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBT = new javax.swing.JButton();
        usernameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        bgLoginLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(710, 730));
        getContentPane().setLayout(null);

        loginBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        loginBT.setBorder(null);
        loginBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTActionPerformed(evt);
            }
        });
        getContentPane().add(loginBT);
        loginBT.setBounds(280, 500, 130, 60);

        usernameTF.setBackground(new java.awt.Color(0, 174, 239));
        usernameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameTF.setForeground(new java.awt.Color(255, 255, 255));
        usernameTF.setBorder(null);
        getContentPane().add(usernameTF);
        usernameTF.setBounds(210, 301, 280, 25);

        passwordTF.setBackground(new java.awt.Color(0, 174, 239));
        passwordTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordTF.setForeground(new java.awt.Color(255, 255, 255));
        passwordTF.setBorder(null);
        getContentPane().add(passwordTF);
        passwordTF.setBounds(210, 388, 280, 25);

        bgLoginLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login_BukuAlamat.png"))); // NOI18N
        bgLoginLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(bgLoginLB);
        bgLoginLB.setBounds(0, 0, 700, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTActionPerformed
        // coding untuk login
        if ((usernameTF.getText().equals("admin")) && (String.valueOf(passwordTF.getPassword()).equals("admin"))){
                new FormBukuAlamat().setVisible(true);
                dispose();
            } else {
                // coding untuk memunculkan pesan kesalahan jika username atau password salah
                JOptionPane.showMessageDialog (
                        null,"Username atau Password Anda salah","Kesalahan",JOptionPane.ERROR_MESSAGE);
                usernameTF.setText("");
                passwordTF.setText("");
                usernameTF.requestFocus();
            }
    }//GEN-LAST:event_loginBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginBukuAlamat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLoginLB;
    private javax.swing.JButton loginBT;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
